'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default
    
    '''<summary>
    '''xslhomepage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xslhomepage As Global.System.Web.UI.WebControls.Xml
    
    '''<summary>
    '''xslprojectsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xslprojectsearch As Global.System.Web.UI.WebControls.Xml
    
    '''<summary>
    '''xsldocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xsldocuments As Global.System.Web.UI.WebControls.Xml
    
    '''<summary>
    '''xslsettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xslsettings As Global.System.Web.UI.WebControls.Xml
    
    '''<summary>
    '''xsllayout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xsllayout As Global.System.Web.UI.WebControls.Xml
    
    '''<summary>
    '''xslsetup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xslsetup As Global.System.Web.UI.WebControls.Xml
    
    '''<summary>
    '''xslcontent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xslcontent As Global.System.Web.UI.WebControls.Xml
    
    '''<summary>
    '''aspxmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspxmessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
