'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Report
    
    '''<summary>
    '''divlogowrapper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divlogowrapper As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''sdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''xslcontent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xslcontent As Global.System.Web.UI.WebControls.Xml
    
    '''<summary>
    '''divhtmlinsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divhtmlinsert As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
